version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongodb_books
    environment:
      - MONGO_INITDB_DATABASE=books
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    networks:
      - mongo-net

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb_books
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    networks:
      - mongo-net
  ingestion:
    image: giselabcr8888/ingestion:latest
    container_name: ingestion
    ports:
      - "7070:7070"
    networks:
      - mongo-net
      - engine-net
    volumes:
      - engine-volume:/app
  indexing:
    image: giselabcr8888/indexing:latest
    container_name: indexing
    environment:
      - MONGO_URL=mongodb://mongodb_books:27017
    ports:
      - "8080:8080"
    networks:
      - mongo-net
      - engine-net
    volumes:
      - engine-volume:/app
  search:
    image: giselabcr8888/search:latest
    container_name: search
    environment:
      - MONGO_URL=mongodb://mongodb_books:27017
    ports:
      - "9090:9090"
    networks:
      - mongo-net
      - engine-net
    volumes:
      - engine-volume:/app/data
  control:
    image: control:latest
    ports:
      - "6060:6060"
    depends_on:
      - indexing
      - ingestion
      - search
    container_name: control
    environment:
      - INGESTION_URL=http://ingestion:7070
      - INDEX_URL=http://indexing:8080
      - SEARCH_URL=http://search:9090
    networks:
      - engine-net
    volumes:
      - engine-volume:/app/data

networks:
  mongo-net:
    driver: bridge
  engine-net:
    driver: bridge
volumes:
  engine-volume:
