version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: search_load_balancer
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - search_net
    depends_on:
      - search1
      - search2
      - search3

  search1:
    image: giselabcr8888/search:latest
    container_name: search1
    expose:
      - "8081"
    networks:
      - search_net

  search2:
    image: giselabcr8888/search:latest
    container_name: search2
    expose:
      - "8082"
    networks:
      - search_net

  search3:
    image: giselabcr8888/search:latest
    container_name: search3
    expose:
      - "8083"
    networks:
      - search_net

networks:
  search_net:
    driver: bridge
